// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CmdInp","status":true,"description":"v1.1.2 CmdInp Enables a Command Input system.","parameters":{"Text Variable":"1","Max Characters":"12","Use Image":"false","Image Name":"ClipComputer","Default Header":"\"This is a Input Window\"","Default InputText":"\"InputText\""}}
];
